module.exports.GameState = {
	INITIALIZATION: 0,
	INITSUMMONPLAYERONEFOOTMANONE: 1,
	INITSUMMONPLAYERONEFOOTMANTWO: 2,
	INITSUMMONPLAYERTWOFOOTMANONE: 3,
	INITSUMMONPLAYERTWOFOOTMANTWO: 4,
	CHOOSECHESS: 5,
	CHOOSEACTION: 6,
	CHOOSEDESTONE: 7,
	CHOOSEDESTTWO: 8,
	ENDSTATE: 9
}
